# Generated by Django 6.0.3 on 2026-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Čeká na odeslání'), ('delivered', 'Doručeno'), ('failed', 'Selhalo')], default='delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('webhook', 'Webhook')], default='in_app', max_length=20),
        ),
    ]
