# Generated by Django 6.0.3 on 2026-03-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body_template', models.TextField(help_text='Template with placeholders: {{client_name}}, {{total_price}}, {{deposit_amount}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_pdf', models.FileField(blank=True, upload_to='contracts/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by_client', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('sent', 'Odesláno'), ('signed', 'Podepsáno'), ('cancelled', 'Zrušeno')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='pipeline.deal')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Záloha'), ('milestone', 'Milník'), ('final', 'Doplatek')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Čeká na platbu'), ('paid', 'Zaplaceno'), ('overdue', 'Po splatnosti')], default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pipeline.deal')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
