# Generated by Django 6.0.3 on 2026-03-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_ok', models.BooleanField(default=False, verbose_name='Výkon — load time < 3s')),
                ('security_ok', models.BooleanField(default=False, verbose_name='Bezpečnost — OWASP top 10')),
                ('responsive_ok', models.BooleanField(default=False, verbose_name='Responzivita — mobile/tablet/desktop')),
                ('cross_browser_ok', models.BooleanField(default=False, verbose_name='Cross-browser — Chrome/Firefox/Safari')),
                ('seo_ok', models.BooleanField(default=False, verbose_name='SEO — meta tagy, sitemap, robots.txt')),
                ('accessibility_ok', models.BooleanField(default=False, verbose_name='Přístupnost — WCAG 2.1 AA')),
                ('backup_ok', models.BooleanField(default=False, verbose_name='Zálohy — automatické zálohy nastaveny')),
                ('monitoring_ok', models.BooleanField(default=False, verbose_name='Monitoring — uptime + error tracking')),
                ('documentation_ok', models.BooleanField(default=False, verbose_name='Dokumentace — API docs, user guide')),
                ('client_training_ok', models.BooleanField(default=False, verbose_name='Školení klienta — provedeno')),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_checklists', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa_checklist', to='projects.project')),
            ],
        ),
    ]
