# Generated by Django 6.0.3 on 2026-03-07 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_populate_milestone_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetemplateitem',
            name='acceptance_criteria',
            field=models.TextField(blank=True, help_text='Kritéria pro schválení (jeden na řádek)'),
        ),
        migrations.AddField(
            model_name='milestonetemplateitem',
            name='deliverables',
            field=models.TextField(blank=True, help_text='Seznam očekávaných výstupů (jeden na řádek)'),
        ),
        migrations.AddField(
            model_name='milestonetemplateitem',
            name='rich_description',
            field=models.TextField(blank=True, help_text='HTML/Markdown obsah pro detailní popis'),
        ),
        migrations.CreateModel(
            name='TemplateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_template_comments', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.milestonetemplate')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.milestonetemplateitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
