# Generated by Django 6.0.3 on 2026-03-06 12:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.CharField(max_length=200)),
                ('client_contact_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('lead', 'Lead'), ('qualification', 'Kvalifikace'), ('pricing', 'Cenotvorba'), ('presentation', 'Prezentace'), ('contract', 'Smlouva'), ('planning', 'Plánování'), ('development', 'Vývoj'), ('completed', 'Dokončeno')], default='lead', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktivní'), ('archived', 'Archivováno'), ('on_hold', 'Pozastaveno')], default='active', max_length=20)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('portal_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase_changed_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pipeline.deal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'deal activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['phase', 'status'], name='pipeline_de_phase_5aa7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['assigned_to', 'status'], name='pipeline_de_assigne_636e45_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['portal_token'], name='pipeline_de_portal__baf1b8_idx'),
        ),
    ]
