# Generated by Django 6.0.3 on 2026-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_ico',
            field=models.CharField(blank=True, max_length=20, verbose_name='IČO'),
        ),
    ]
