# Generated by Django 6.0.3 on 2026-03-07 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_add_deal_client_ico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lead_documents/')),
                ('raw_text', models.TextField(blank=True, help_text='Vložený text (pokud není soubor)')),
                ('document_type', models.CharField(choices=[('email', 'Email'), ('brief', 'Brief'), ('rfp', 'RFP'), ('meeting_notes', 'Poznámky ze schůzky'), ('other', 'Jiné')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Čeká na zpracování'), ('processing', 'Zpracovává se'), ('processed', 'Zpracováno'), ('failed', 'Chyba')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Data extrahovaná AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='pipeline.deal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
