# Generated by Django 6.0.3 on 2026-03-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_add_lead_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="portal_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="portal_token_last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
