# Generated by Django 6.0.3 on 2026-03-10 04:08

from datetime import timedelta

from django.db import migrations
from django.utils import timezone


def set_expiration(apps, schema_editor):
    Deal = apps.get_model("pipeline", "Deal")
    now = timezone.now()
    # Active deals: 90 days
    Deal.objects.filter(status="active").update(
        portal_token_expires_at=now + timedelta(days=90)
    )
    # Archived/on_hold deals: 30 days
    Deal.objects.exclude(status="active").update(
        portal_token_expires_at=now + timedelta(days=30)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_add_portal_token_expiration"),
    ]

    operations = [
        migrations.RunPython(set_expiration, migrations.RunPython.noop),
    ]
