# Generated by Django 6.0.3

from django.db import migrations


def populate_client_companies(apps, schema_editor):
    """Group deals by (client_company, client_email) and create ClientCompany records."""
    Deal = apps.get_model("pipeline", "Deal")
    ClientCompany = apps.get_model("pipeline", "ClientCompany")

    seen = {}
    for deal in Deal.objects.all().order_by("created_at"):
        key = (deal.client_company.strip().lower(), deal.client_email.strip().lower())
        if key not in seen:
            cc = ClientCompany.objects.create(
                name=deal.client_company,
                contact_name=deal.client_contact_name,
                email=deal.client_email,
                phone=deal.client_phone,
                ico=deal.client_ico,
            )
            seen[key] = cc
        deal.client = seen[key]
        deal.save(update_fields=["client"])


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_add_client_company"),
    ]

    operations = [
        migrations.RunPython(populate_client_companies, migrations.RunPython.noop),
    ]
