# Generated by Django 6.0.3 on 2026-03-10 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial_company_models'),
        ('pipeline', '0007_populate_client_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company'),
        ),
    ]
