# Generated by Django 6.0.3 on 2026-03-06 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "hours": 10, "rate": 1500, "total": 15000}]')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('demo_url', models.URLField(blank=True)),
                ('demo_description', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Koncept'), ('sent', 'Odesláno'), ('accepted', 'Přijato'), ('rejected', 'Zamítnuto'), ('expired', 'Expirováno')], default='draft', max_length=20)),
                ('client_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='pipeline.deal')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('deal', 'version')},
            },
        ),
    ]
