# Generated by Django 6.0.3 on 2026-03-07 05:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Category key (e.g., custom_dev)', max_length=50, unique=True)),
                ('category_label', models.CharField(help_text='Display label', max_length=100)),
                ('base_hours', models.PositiveIntegerField(default=80)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('1500'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing matrices',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='PricingModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(choices=[('user_count', 'User Count'), ('complexity', 'Complexity'), ('design', 'Design Requirements'), ('platform', 'Platform')], max_length=20)),
                ('key', models.CharField(help_text='Value key (e.g., 1_5, 6_20)', max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4)),
                ('extra_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['modifier_type', 'key'],
                'unique_together': {('modifier_type', 'key')},
            },
        ),
    ]
